WIP: Initial tech radar
lhsystems/technology-radar pull request #4
Opened 2020-11-20 16:39 UTC by KrishnanSankaran

2020-11-22 13:17 UTC, wagnst commented
@lhsystems/technology-coe pls have a look to this PR.

2020-11-24 07:45 UTC, danielmohacsi commented
If anybody wants to preview this PR as a tech radar, you can do it [here](https://radar.thoughtworks.com/?sheetId=https%3A%2F%2Fraw.githubusercontent.com%2Flhsystems%2Ftechnology-radar%2Finitial-tech-radar%2FLufthansa%2520Systems%2520Tech%2520Radar.csv)

2020-11-24 08:04 UTC, danielmohacsi commented
@KrishnanSankaran @wagnst I have a general question about the items on the radar.
How do we interpret _Hold_, _Assess_, _Trial_ and _Adopt_?
Have you checked the Thoughtworks Radar FAQ? https://www.thoughtworks.com/radar/faq
Do we follow these definitions?

2020-11-24 10:01 UTC, KrishnanSankaran commented
> @KrishnanSankaran @wagnst I have a general question about the items on the radar.
> How do we interpret _Hold_, _Assess_, _Trial_ and _Adopt_?
> Have you checked the Thoughtworks Radar FAQ? https://www.thoughtworks.com/radar/faq
> Do we follow these definitions?

@danielmohacsi I did my best to follow Thoughtworks definition for _Hold_, _Assess_, _Trial_ and _Adopt_. In case you found something thats strange, do please provide me hints. Also, as this is our initial version, it also takes into account the existing skill set of our engineers - perhaps some might be removed in later versions (after skillset upgrades etc).

2020-11-24 15:25 UTC, wagnst requested changes
Please check the comments inline.

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +Infrastructure as code,Adopt,Techniques,FALSE,"<p>Although <strong>infrastructure as code</strong> is a relatively old technique (we’ve featured it in the Radar in 2011), it has become vitally import
Which Radar from 2011 you are referring to?

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +SaaS and Multi-Tenancy,Adopt,Techniques,FALSE,"<p>We commit ourselves in developing/modernizing our applications (and its architecture) to be <strong><a href=""https://en.wikipedia.org/wiki/Multitena
Maybe SaaS and multi-tenancy are two set of shoes - although I do understand what you mean. Maybe the vision of SaaS enabled products can be listed separately?

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +Firebase Cloud Messaging (FCM),Adopt,Platforms,FALSE,"<p>With <strong><a href=""https://firebase.google.com/docs/cloud-messaging"">Firebase Cloud Messaging (FCM)</a></strong> we setup reliable and ba
Is this what we really want to adopt? How is this technology abstracting the multi-cloud vision? Also is this a recommendation from CNCF for this problem pattern?

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +Business intelligence (BI) platform,Adopt,Platforms,FALSE,"<p><strong><a href=""https://www.gartner.com/en/information-technology/glossary/bi-platforms"">BI Platforms</a></strong> enable us to build
I would rather like to see here the specific technology that we chose rather than the general pattern, cause for be BI itself is not a platform. Tableau or PowerBI would be.

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +Tyk API platform,Assess,Platforms,FALSE,"<p><strong><a href=""https://tyk.io/"">Tyk</a></strong> as an API platform, is a set of tools to manage lifecycle of our application APIs (internal, partnet a
Isnt this overlapping with 

> API Management

 in line 6?

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +Mariadb,Adopt,Tools,FALSE,"<p><strong><a href=""https://www.postgresql.org/"">MariaDB</a></strong> is one of the most popular open source relational databases and it is part of most cloud offerings.
Please check correct spelling of  CamelCase. MariaDB not Mariadb or MariaDb.

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +Hazelcast,Adopt,Tools,FALSE,"<p><strong><a href=""https://github.com/hazelcast/hazelcast"">Hazelcast</a></strong> is an open source distributed in-memory data store, highly optimized and with low lat
Why have two tools for the same problem? Below is Redis. We only need one.

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +Redis,Adopt,Tools,FALSE,"<p><strong><a href=""https://redis.io/"">Redis</a></strong> is an open source, in-memory data structure store, used as a distributed cache in our event-driven and distributed
Why have two tools for the same problem? Above is Hazelcast. We only need one.

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +Keycloak,Adopt,Tools,FALSE,"<p><strong><a href=""https://www.keycloak.org/"">Keycloak</a></strong> is an open source Identity and Access Management (IAM) tool aimed at modern applications and service
Please check with Michael Otte as he is actively investigating the IAM topic as well. Just to double check.

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +Apigee,Adopt,Tools,FALSE,"<p><strong><a href=""https://cloud.google.com/apigee"">Apigee</a></strong> is a platform for developing and managing APIs and provides an abstraction to our backend service
Again somehow duplicating what is in 

> API Management

and

> Tyk API platform

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +Mashery,Adopt,Tools,FALSE,"<p><strong><a href=""https://www.tibco.com/de/products/api-management"">Mashery</a></strong> delivers rich capabilities to our API Management requirements and we believe it
Overlap with the Eventmesh, API management, Tyk API and Apigee? Why so many tools in the first place?

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +Kafka,Adopt,Tools,FALSE,"<p><strong><a href=""https://kafka.apache.org/"">Kafka</a></strong> our primary event streaming and message broker for event-driven applications.</p>"
We already have event mesh somewhere...

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +Camunda BPMN Engine,Adopt,Tools,FALSE,"<p><strong><a href=""https://camunda.com/"">Camunda</a></strong>, an opensource workflow automation tool allows automating our business processes and achieve di
Drools vs Camunda? Dont put both here until its not decided...

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +Drools Business Rule Engine,Adopt,Tools,FALSE,"<p><strong><a href=""https://www.drools.org/"">Drools</a></strong> is one of the most popular Business Rules Management Systems (BRMS) solution and its
Drools vs Camunda? Dont put both here until its not decided...

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +CoreDNS,Adopt,Tools,FALSE,"<p><strong><a href=""https://coredns.io/"">CoreDNS</a></strong> is our prefered choice for DNS and Service Discovery when running applications in <a href=""https://kubernet
Actually not completely, as CoreDNS does not solve how the zones are resolved externally. Therefore we need also other tools like externalDNS.

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +Apigee developer portal,Adopt,Tools,FALSE,"<p><strong><a href=""https://cloud.google.com/apigee/api-management/developer-portal"">Apigee developer portal</a></strong> is a promising choice to support
apigee is already above, duplication?

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +OWASP Dependency-Check,Adopt,Tools,FALSE,"<p><strong><a href=""https://owasp.org/www-project-dependency-check/"">OWASP Dependency Check</a></strong> to detect publicly disclosed vulnerabilities conta
Maybe we would like to adopt rather a tool that is builtin the future artifact storage like [X-Ray](https://jfrog.com/xray/) @danielmohacsi

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
>  Open Policy Agent (OPA),Trial,Tools,FALSE,"<p><strong><a href=""https://www.openpolicyagent.org/"">Open Policy Agent (OPA)</a></strong> has rapidly become a favorable component of many distributed cl
Also add Hashicorp Sentinel maybe as specific usage might happen in GitOps.

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +Mural,Trial,Tools,FALSE,"<p><strong><a href=""https://www.mural.co/"">MURAL</a></strong> is a ""digital workspace for visual collaboration"" and allows teams to interact with a shared workspace based
Guess its not trial anymore, rather adopt.

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +Apiman,Assess,Tools,FALSE,"<p>Being an open source API Management toolset, <strong><a href=""https://www.apiman.io/latest/"">Apiman</a></strong> is a promising choice for publishing our APIs, enforci
Another API management?

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +Gravitee,Assess,Tools,FALSE,"<p><strong><a href=""https://www.gravitee.io/"">Gravitee</a></strong> as an open source API Management toolset, is a promising choice to manage API lifecycle and monetize
Another API management?

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +OpenMetrics,Assess,Tools,FALSE,"<p><strong><a href=""https://openmetrics.io/"">OpenMetrics</a></strong> is the de-facto standard for transmitting metrics and we want to evaluate its usage in our dist
thats not really a tool...

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +Kong developer portal,Assess,Tools,FALSE,"<p><strong><a href=""https://konghq.com/products/kong-enterprise/dev-portal/"">Kong Developer Portal</a></strong> provides a single source of truth to locate
we have kong already, why add developer portal explicitly?

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +.NET/C#,Adopt,languages-and-frameworks,FALSE,"<p><strong><a href=""https://dotnet.microsoft.com/learn/dotnet/what-is-dotnet"">.Net</a></strong> is a free, cross-platform, open source developer platfo
Did we align already that we want to adopt these technologies? Or rather put them on hold?

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +JavaScript/TypeScript,Adopt,languages-and-frameworks,FALSE,"<p><strong><a href=""https://www.typescriptlang.org/"">Typescript</a></strong> is a modern age <strong><a href=""https://en.wikipedia.org/w
When we add react or angular, is there the need to add JS here?

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +resilience4j,Adopt,languages-and-frameworks,FALSE,"<p><strong><a href=""https://github.com/resilience4j/resilience4j"">resilience4j</a></strong> is our lightweight fault tolerance library for Java 8
looks too much detailed, not sure its needed.

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +Quartz Scheduler,Adopt,languages-and-frameworks,FALSE,"<p><strong><a href=""http://www.quartz-scheduler.org/"">Quartz</a></strong> is our preferred job scheduling framework for java based application
overlapping with the BPMN engines listed above?

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +Swift (iOS Native Apps),Trial,languages-and-frameworks,FALSE,"<p><strong><a href=""https://www.apple.com/swift/"">Swift</a></strong> for creating iOS native apps.</p>"
we said to ignore mobile technologies for now.

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +eCharts,Trial,languages-and-frameworks,FALSE,"<p><strong><a href=""https://echarts.apache.org/en/index.html"">eCharts</a></strong> is our preferred open-sourced JavaScript charting library to create
UI not in focus for now.

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +Progressive Web Apps(PWA),Trial,languages-and-frameworks,FALSE,"<p><strong><a href=""https://web.dev/what-are-pwas/"">Java</a></strong> for creating apps reaching anyone, anywhere, on any device with
we said to ignore mobile technologies for now.

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +Cordova,Trial,languages-and-frameworks,FALSE,"<p><strong><a href=""https://cordova.apache.org/"">Cordova</a></strong> for developing mobile apps targettig multiple platforms with one codebase.</p>"
we said to ignore mobile technologies for now.

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +Cordova Geofence,Trial,languages-and-frameworks,FALSE,"<p><strong><a href=""https://github.com/cowbell/cordova-plugin-geofence"">Cordova Geofencing</a></strong> for geofencing capabilities in our mob
we said to ignore mobile technologies for now.

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +Bitronix,Assess,languages-and-frameworks,FALSE,"<p><strong><a href=""https://github.com/bitronix/btm"">Bitronix</a></strong> our XA transaction manager as an implementation of JTA 1.1 API.</p>"
really needed in that detail level?

2020-11-24 15:25 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +LIXA (XTA),Assess,languages-and-frameworks,FALSE,"<p><strong><a href=""https://dzone.com/articles/microservices-and-distributed-transactions"">LIXA (XTA)</a></strong> our XTA transaction manager and
really needed in that detail level?

2020-11-25 06:33 UTC, danielmohacsi commented on Lufthansa Systems Tech Radar.csv
> +Infrastructure as code,Adopt,Techniques,FALSE,"<p>Although <strong>infrastructure as code</strong> is a relatively old technique (we’ve featured it in the Radar in 2011), it has become vitally import
This is a copy-paste from Thoughtworks

2020-11-25 06:55 UTC, danielmohacsi commented
@KrishnanSankaran @wagnst I think we could even get more out of the tech radar if we defined adopt, assess, trial and hold a little bit differently. For me adopt would mean that the certain blip is being used at least by one of the core domain products at the company, with success in production.

2020-11-25 06:57 UTC, danielmohacsi requested changes
Looks good to me, but let's remove docker from the hold ring for now, because it is misleading

2020-11-25 06:57 UTC, danielmohacsi commented on Lufthansa Systems Tech Radar.csv
> +Micro frontends,Adopt,Techniques,FALSE,"<p><strong><a href=""https://micro-frontends.org/"">Micro-frontends</a></strong> extends the concepts of <strong><a href=""https://martinfowler.com/articles/mi
In my opinion, this should be in the Trial/Assess ring.

2020-11-25 06:57 UTC, danielmohacsi commented on Lufthansa Systems Tech Radar.csv
> +Feature toggle,Trial,Techniques,FALSE,"<p><strong><a href=""https://www.thoughtworks.com/radar/techniques/simplest-possible-feature-toggle"">Feature toggles</a></strong> are powerful technique to mod
This is already adopted by some products

2020-11-25 06:57 UTC, danielmohacsi commented on Lufthansa Systems Tech Radar.csv
> +Docker,Hold,Tools,FALSE,"<p><strong><a href=""https://www.docker.com/"">Docker</a></strong> is to be used only if a managed <a href=""https://kubernetes.io/"">Kubernetes</a> transparently uses it as
I find it misleading that docker is in the hold ring. I agree that there are better suited tools around for building OCI images, like kaniko or buildah, but for developers docker is still a very useful and easy tool to get started with containerization (the first step of the cncf trail map).
I suggest removing this blip.

2020-11-25 07:24 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Infrastructure as code,Adopt,Techniques,FALSE,"<p>Although <strong>infrastructure as code</strong> is a relatively old technique (we’ve featured it in the Radar in 2011), it has become vitally import
It is indeed a copy-paste, though I corrected some parts, this "2011" escaped my eyes. Have correct and upload a new version soon.

2020-11-25 07:30 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +SaaS and Multi-Tenancy,Adopt,Techniques,FALSE,"<p>We commit ourselves in developing/modernizing our applications (and its architecture) to be <strong><a href=""https://en.wikipedia.org/wiki/Multitena
Agreed & done. Will be part of next upload.

2020-11-25 07:45 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Business intelligence (BI) platform,Adopt,Platforms,FALSE,"<p><strong><a href=""https://www.gartner.com/en/information-technology/glossary/bi-platforms"">BI Platforms</a></strong> enable us to build
Agreed & done, part of upcoming upload.

2020-11-25 07:47 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Tyk API platform,Assess,Platforms,FALSE,"<p><strong><a href=""https://tyk.io/"">Tyk</a></strong> as an API platform, is a set of tools to manage lifecycle of our application APIs (internal, partnet a
somewhat yes, but its a platform (comprising of multiple tools) to support API management and more. I feel, we should assess it and explicitly decide on its use/rejection.

2020-11-25 07:51 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Mariadb,Adopt,Tools,FALSE,"<p><strong><a href=""https://www.postgresql.org/"">MariaDB</a></strong> is one of the most popular open source relational databases and it is part of most cloud offerings.
done, will be part of upcoming upload.

2020-11-25 07:52 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Hazelcast,Adopt,Tools,FALSE,"<p><strong><a href=""https://github.com/hazelcast/hazelcast"">Hazelcast</a></strong> is an open source distributed in-memory data store, highly optimized and with low lat
Done, i choose Hazelcast :-)

2020-11-25 07:52 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Redis,Adopt,Tools,FALSE,"<p><strong><a href=""https://redis.io/"">Redis</a></strong> is an open source, in-memory data structure store, used as a distributed cache in our event-driven and distributed
Done, i choose Hazelcast :-)

2020-11-25 07:53 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Apigee,Adopt,Tools,FALSE,"<p><strong><a href=""https://cloud.google.com/apigee"">Apigee</a></strong> is a platform for developing and managing APIs and provides an abstraction to our backend service
Apigee is a tool and API Management is a technique. IMO, we need both to get buy-in and its acceptance. I prefer to leave it as it is. OK?

2020-11-25 07:56 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Camunda BPMN Engine,Adopt,Tools,FALSE,"<p><strong><a href=""https://camunda.com/"">Camunda</a></strong>, an opensource workflow automation tool allows automating our business processes and achieve di
Drools is rule engine and Camunda is workflow engine. some parts overlap but they are used for different purposes, hence both.

2020-11-25 07:57 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Mashery,Adopt,Tools,FALSE,"<p><strong><a href=""https://www.tibco.com/de/products/api-management"">Mashery</a></strong> delivers rich capabilities to our API Management requirements and we believe it
Moving Mashery to assess, it is used in DLH. Apigee is used in miles-and-mores. I keep Apigee and move Mashery to assess. OK?

2020-11-25 07:58 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Drools Business Rule Engine,Adopt,Tools,FALSE,"<p><strong><a href=""https://www.drools.org/"">Drools</a></strong> is one of the most popular Business Rules Management Systems (BRMS) solution and its
Drools is rule engine and Camunda is workflow engine. some parts overlap but they are used for different purposes, hence both

2020-11-25 07:59 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Apigee developer portal,Adopt,Tools,FALSE,"<p><strong><a href=""https://cloud.google.com/apigee/api-management/developer-portal"">Apigee developer portal</a></strong> is a promising choice to support
potentially yes, hence removed.

2020-11-25 08:00 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Mural,Trial,Tools,FALSE,"<p><strong><a href=""https://www.mural.co/"">MURAL</a></strong> is a ""digital workspace for visual collaboration"" and allows teams to interact with a shared workspace based
done.

2020-11-25 08:00 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +Mashery,Adopt,Tools,FALSE,"<p><strong><a href=""https://www.tibco.com/de/products/api-management"">Mashery</a></strong> delivers rich capabilities to our API Management requirements and we believe it
But noone uses it in LSY or not?

2020-11-25 08:01 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Kong developer portal,Assess,Tools,FALSE,"<p><strong><a href=""https://konghq.com/products/kong-enterprise/dev-portal/"">Kong Developer Portal</a></strong> provides a single source of truth to locate
Agree and removed!

2020-11-25 08:05 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +.NET/C#,Adopt,languages-and-frameworks,FALSE,"<p><strong><a href=""https://dotnet.microsoft.com/learn/dotnet/what-is-dotnet"">.Net</a></strong> is a free, cross-platform, open source developer platfo
I am putting it on assess rather than on-hold.. OK? It was a suggestion coming from someone.

2020-11-25 08:06 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +JavaScript/TypeScript,Adopt,languages-and-frameworks,FALSE,"<p><strong><a href=""https://www.typescriptlang.org/"">Typescript</a></strong> is a modern age <strong><a href=""https://en.wikipedia.org/w
removed..

2020-11-25 08:07 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +resilience4j,Adopt,languages-and-frameworks,FALSE,"<p><strong><a href=""https://github.com/resilience4j/resilience4j"">resilience4j</a></strong> is our lightweight fault tolerance library for Java 8
I would leave it in there for gaining initial buy-in

2020-11-25 08:07 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Quartz Scheduler,Adopt,languages-and-frameworks,FALSE,"<p><strong><a href=""http://www.quartz-scheduler.org/"">Quartz</a></strong> is our preferred job scheduling framework for java based application
Nope, not really.

2020-11-25 08:10 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Swift (iOS Native Apps),Trial,languages-and-frameworks,FALSE,"<p><strong><a href=""https://www.apple.com/swift/"">Swift</a></strong> for creating iOS native apps.</p>"
OK, removed for now. I would actually prefer to have it in assess atleast.

2020-11-25 08:10 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +eCharts,Trial,languages-and-frameworks,FALSE,"<p><strong><a href=""https://echarts.apache.org/en/index.html"">eCharts</a></strong> is our preferred open-sourced JavaScript charting library to create
OK, removed for now. I would actually prefer to have it in assess atleast.

2020-11-25 08:10 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Progressive Web Apps(PWA),Trial,languages-and-frameworks,FALSE,"<p><strong><a href=""https://web.dev/what-are-pwas/"">Java</a></strong> for creating apps reaching anyone, anywhere, on any device with
OK, removed for now. I would actually prefer to have it in assess atleast.

2020-11-25 08:10 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Cordova,Trial,languages-and-frameworks,FALSE,"<p><strong><a href=""https://cordova.apache.org/"">Cordova</a></strong> for developing mobile apps targettig multiple platforms with one codebase.</p>"
OK, removed for now. I would actually prefer to have it in assess atleast.

2020-11-25 08:10 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Cordova Geofence,Trial,languages-and-frameworks,FALSE,"<p><strong><a href=""https://github.com/cowbell/cordova-plugin-geofence"">Cordova Geofencing</a></strong> for geofencing capabilities in our mob
OK, removed for now. I would actually prefer to have it in assess atleast.

2020-11-25 08:12 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Bitronix,Assess,languages-and-frameworks,FALSE,"<p><strong><a href=""https://github.com/bitronix/btm"">Bitronix</a></strong> our XA transaction manager as an implementation of JTA 1.1 API.</p>"
One important aspect which is normally left out. I prefer to keep it (in assess phase).

2020-11-25 08:12 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +LIXA (XTA),Assess,languages-and-frameworks,FALSE,"<p><strong><a href=""https://dzone.com/articles/microservices-and-distributed-transactions"">LIXA (XTA)</a></strong> our XTA transaction manager and
removed this one, will include if analysis result is positive.

2020-11-25 08:14 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Docker,Hold,Tools,FALSE,"<p><strong><a href=""https://www.docker.com/"">Docker</a></strong> is to be used only if a managed <a href=""https://kubernetes.io/"">Kubernetes</a> transparently uses it as
I have moved docker to Assess. Its currently used but is not our choice in future. OK ?

2020-11-25 08:16 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Feature toggle,Trial,Techniques,FALSE,"<p><strong><a href=""https://www.thoughtworks.com/radar/techniques/simplest-possible-feature-toggle"">Feature toggles</a></strong> are powerful technique to mod
You are right that some have adopted this but it is still in an early stage. Hence I prefer to keep it in Trail, OK ?

2020-11-25 08:17 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Micro frontends,Adopt,Techniques,FALSE,"<p><strong><a href=""https://micro-frontends.org/"">Micro-frontends</a></strong> extends the concepts of <strong><a href=""https://martinfowler.com/articles/mi
OK with your suggestion. Moved it to Trial.

2020-11-25 08:19 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +OpenMetrics,Assess,Tools,FALSE,"<p><strong><a href=""https://openmetrics.io/"">OpenMetrics</a></strong> is the de-facto standard for transmitting metrics and we want to evaluate its usage in our dist
moved to languages-and-frameworks

2020-11-25 08:19 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Apiman,Assess,Tools,FALSE,"<p>Being an open source API Management toolset, <strong><a href=""https://www.apiman.io/latest/"">Apiman</a></strong> is a promising choice for publishing our APIs, enforci
I would leave it in Assess..

2020-11-25 08:20 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Gravitee,Assess,Tools,FALSE,"<p><strong><a href=""https://www.gravitee.io/"">Gravitee</a></strong> as an open source API Management toolset, is a promising choice to manage API lifecycle and monetize
removed!

2020-11-25 08:26 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Firebase Cloud Messaging (FCM),Adopt,Platforms,FALSE,"<p>With <strong><a href=""https://firebase.google.com/docs/cloud-messaging"">Firebase Cloud Messaging (FCM)</a></strong> we setup reliable and ba
It is one of industry leading platform for sending push notifications and is used in few other products as well (we use it in NL-Crew). I will keep it.

2020-11-25 10:49 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Mashery,Adopt,Tools,FALSE,"<p><strong><a href=""https://www.tibco.com/de/products/api-management"">Mashery</a></strong> delivers rich capabilities to our API Management requirements and we believe it
Usage of Mashery in LSY is not known to me - LHG being our mother, we need to respect their recommendataion :-), hence keep it in assess.

2020-11-25 10:53 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Keycloak,Adopt,Tools,FALSE,"<p><strong><a href=""https://www.keycloak.org/"">Keycloak</a></strong> is an open source Identity and Access Management (IAM) tool aimed at modern applications and service
Have got in touch with Michael, will adapt once he replies back.

2020-11-25 10:55 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Kafka,Adopt,Tools,FALSE,"<p><strong><a href=""https://kafka.apache.org/"">Kafka</a></strong> our primary event streaming and message broker for event-driven applications.</p>"
I would still prefer to have Kafka explicitly in there as a tool. Its visibility is required and a push for its adoption in products. I am convincing NLC to move away from Oracle Advance Queue and go in direction of Kafka. Having it here will really help a lot.

2020-11-25 10:56 UTC, renelippert approved these changes
I am done.
Please consider my comments as hints to think them over. What ever answer you come up with is the right one. :-)

2020-11-25 10:56 UTC, renelippert commented on Lufthansa Systems Tech Radar.csv
> +Domain Driven Design,Adopt,Techniques,FALSE,"<p>Use <strong><a href=""https://en.wikipedia.org/wiki/Domain-driven_design"">Domain Driven Design</a></strong> concepts and principles for decomposing ou
Should we also add TDD - Test Driven Development?

2020-11-25 10:56 UTC, renelippert commented on Lufthansa Systems Tech Radar.csv
> +JMeter,Adopt,Tools,FALSE,"<p><strong><a href=""https://jmeter.apache.org/"">JMeter</a></strong> is our designated service performance testing tool.</p>"
Should we also list here other testing tools like SoapUI?

2020-11-25 10:56 UTC, renelippert commented on Lufthansa Systems Tech Radar.csv
> +Logback for SL4J,Adopt,languages-and-frameworks,FALSE,"<p><strong><a href=""http://logback.qos.ch/"">Logback</a></strong>, our logging framework for java applications.</p>"
Do we need both Logback and Log4j2?

2020-11-25 11:58 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Keycloak,Adopt,Tools,FALSE,"<p><strong><a href=""https://www.keycloak.org/"">Keycloak</a></strong> is an open source Identity and Access Management (IAM) tool aimed at modern applications and service
We keep Keycloak as "Adopt" and include others when analysis is done.

2020-11-25 12:02 UTC, danielmohacsi commented on Lufthansa Systems Tech Radar.csv
> +Feature toggle,Trial,Techniques,FALSE,"<p><strong><a href=""https://www.thoughtworks.com/radar/techniques/simplest-possible-feature-toggle"">Feature toggles</a></strong> are powerful technique to mod
Well, I know about a very important product in one of the core domains who are using feature flags in production for more than a year. Definitely more than a trial.

2020-11-25 12:05 UTC, danielmohacsi commented on Lufthansa Systems Tech Radar.csv
> +Docker,Hold,Tools,FALSE,"<p><strong><a href=""https://www.docker.com/"">Docker</a></strong> is to be used only if a managed <a href=""https://kubernetes.io/"">Kubernetes</a> transparently uses it as
Why do you say it's not our choice? I know Docker desktop is being used by many developers on their company laptop, who dont really have other options.
I think we have to elaborate on this.

2020-11-25 12:07 UTC, danielmohacsi commented on Lufthansa Systems Tech Radar.csv
> -Infrastructure as code,Adopt,Techniques,FALSE,"<p>DEMO Although <strong>infrastructure as code</strong> is a relatively old technique (we’ve featured it in the Radar in 2011), it has become vitally i
Why do we remove IaC from the radar? I think it's still relevant.

2020-11-25 12:09 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +OWASP Dependency-Check,Adopt,Tools,FALSE,"<p><strong><a href=""https://owasp.org/www-project-dependency-check/"">OWASP Dependency Check</a></strong> to detect publicly disclosed vulnerabilities conta
added JFrog Xray in "Assess" for now. Based on the outcome, we upgrade it to Adopt. OK ?

2020-11-25 12:15 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
>  Open Policy Agent (OPA),Trial,Tools,FALSE,"<p><strong><a href=""https://www.openpolicyagent.org/"">Open Policy Agent (OPA)</a></strong> has rapidly become a favorable component of many distributed cl
Included it in "Assess". Based on outcome, we can upgrade it to Trial/Adopt.

2020-11-25 12:19 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Domain Driven Design,Adopt,Techniques,FALSE,"<p>Use <strong><a href=""https://en.wikipedia.org/wiki/Domain-driven_design"">Domain Driven Design</a></strong> concepts and principles for decomposing ou
Including it in the next upload.

2020-11-25 12:19 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +JMeter,Adopt,Tools,FALSE,"<p><strong><a href=""https://jmeter.apache.org/"">JMeter</a></strong> is our designated service performance testing tool.</p>"
Including it in the next upload.

2020-11-25 12:21 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Logback for SL4J,Adopt,languages-and-frameworks,FALSE,"<p><strong><a href=""http://logback.qos.ch/"">Logback</a></strong>, our logging framework for java applications.</p>"
I prefer keeping both at this moment, there are stakeholders who prefer one or other. Based on future analysis, we can decide on one.

2020-11-25 12:22 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> -Infrastructure as code,Adopt,Techniques,FALSE,"<p>DEMO Although <strong>infrastructure as code</strong> is a relatively old technique (we’ve featured it in the Radar in 2011), it has become vitally i
Its not removed, it is very much relevant. Its moved down.

2020-11-25 14:03 UTC, mwilmes approved these changes

2020-11-26 22:08 UTC, renelippert approved these changes

2020-11-27 07:41 UTC, danielmohacsi commented on Lufthansa Systems Tech Radar.csv
> +Docker,Assess,Tools,FALSE,"<p><strong><a href=""https://www.docker.com/"">Docker</a></strong> is to be used only if a managed <a href=""https://kubernetes.io/"">Kubernetes</a> transparently uses it a
Please update the description with something that states that it's still okay to use docker desktop and compose for development purposes on the local machine. Perhaps we could change the name of this blip to docker build to be less misleading.

2020-11-27 07:42 UTC, danielmohacsi commented on Lufthansa Systems Tech Radar.csv
> +Docker,Hold,Tools,FALSE,"<p><strong><a href=""https://www.docker.com/"">Docker</a></strong> is to be used only if a managed <a href=""https://kubernetes.io/"">Kubernetes</a> transparently uses it as
Resolving, since this is outdated

2020-11-29 11:34 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +Logback for SL4J,Adopt,languages-and-frameworks,FALSE,"<p><strong><a href=""http://logback.qos.ch/"">Logback</a></strong>, our logging framework for java applications.</p>"
But there is no reason to do so. I can't think of a legitimate reason except personal preferences.

2020-11-30 09:47 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +Docker,Assess,Tools,FALSE,"<p><strong><a href=""https://www.docker.com/"">Docker</a></strong> is to be used only if a managed <a href=""https://kubernetes.io/"">Kubernetes</a> transparently uses it a
Yes I see two reasons why docker is still fine:
A) on local dev machine (although the others are preferred)
B) if K8s PaaS service (e.g. AKS or GKE) did not yet upgrade to something else than docker (because we do no manage it)
Therefore my vote for docker actually goes to **hold**

2020-11-30 09:59 UTC, wagnst requested changes
Only some minor things and it will be good to go!

2020-11-30 09:59 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +Feature toggle,Trial,Techniques,FALSE,"<p><strong><a href=""https://www.thoughtworks.com/radar/techniques/simplest-possible-feature-toggle"">Feature toggles</a></strong> are powerful technique to mod
And we want to adopt it anyway as its the de-facto standard - agree with @danielmohacsi

2020-11-30 09:59 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +Firebase Cloud Messaging (FCM),Adopt,Platforms,FALSE,"<p>With <strong><a href=""https://firebase.google.com/docs/cloud-messaging"">Firebase Cloud Messaging (FCM)</a></strong> we setup reliable and ba
@mwilmes do you have an idea here? Do you use this in BC by any chance?

2020-11-30 09:59 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +CoreDNS,Adopt,Tools,FALSE,"<p><strong><a href=""https://coredns.io/"">CoreDNS</a></strong> is our prefered choice for DNS and Service Discovery when running applications in <a href=""https://kubernet
I added #5 for this

2020-11-30 09:59 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +EDB,Adopt,Tools,FALSE,"<p><strong><a href=""https://www.enterprisedb.com/"">EDB</a></strong> as an intermediate tool to migrate from OracleDB to PostgreSQL.</p>"
Can you use the full name which is EnterpriseDB?

2020-11-30 09:59 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +resilience4j,Adopt,languages-and-frameworks,FALSE,"<p><strong><a href=""https://github.com/resilience4j/resilience4j"">resilience4j</a></strong> is our lightweight fault tolerance library for Java 8
My impression is still that its way to detailed for a tech radar. @danielmohacsi @mwilmes any ideas on this one?

2020-11-30 09:59 UTC, wagnst commented on Lufthansa Systems Tech Radar.csv
> +Logback for SL4J,Adopt,languages-and-frameworks,FALSE,"<p><strong><a href=""http://logback.qos.ch/"">Logback</a></strong>, our logging framework for java applications.</p>"
There was a comment by another colleague on Jira who mentioned correct spelling is "SL4J - typo: is called Simple Logging Facade for Java, hence **SLF4J**"

2020-11-30 14:42 UTC, u724952 requested changes
just pointed out some typos, and a suggestion regarding documentation (instead of Arc42 - which might be "hold", add docs-as-code)

2020-11-30 14:42 UTC, u724952 commented on Lufthansa Systems Tech Radar.csv
> +Arc42,Adopt,Techniques,FALSE,"<p><strong><a href=""https://docs.arc42.org/home/"">Arc42</a></strong> is our standard way for documenting and communicating software and system architectures.</p>"
instead of (or besides) this, we should mention somewhere "docs as code", i am not aware of any project happily maintaining Arc42 docs

2020-11-30 14:42 UTC, u724952 commented on Lufthansa Systems Tech Radar.csv
> +Strangler Pattern,Adopt,Techniques,FALSE,"<p><strong><a href=""https://microservices.io/patterns/refactoring/strangler-application.html"">Stranler Pattern</a></strong>  to incrementally transform out
there is a typo in description, "stranler"

2020-11-30 14:42 UTC, u724952 commented on Lufthansa Systems Tech Radar.csv
> +Test Driven Development,Adopt,Techniques,FALSE,"<p><strong><a href=""https://en.wikipedia.org/wiki/Test-driven_development"">Test Driven Development (TDD)</a></strong> as a test-first practice when d
typo in description "deveoping"

2020-11-30 14:42 UTC, u724952 commented on Lufthansa Systems Tech Radar.csv
> +Log4j2 for SL4J,Adopt,languages-and-frameworks,FALSE,"<p><strong><a href=""https://logging.apache.org/log4j/2.x/"">Log4j2</a></strong>, our alternate logging framework for java applications.</p>"
same here are in previous line: the framework is called SLF4J

2020-12-08 08:11 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Strangler Pattern,Adopt,Techniques,FALSE,"<p><strong><a href=""https://microservices.io/patterns/refactoring/strangler-application.html"">Stranler Pattern</a></strong>  to incrementally transform out
done and part of next upload

2020-12-08 08:11 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Test Driven Development,Adopt,Techniques,FALSE,"<p><strong><a href=""https://en.wikipedia.org/wiki/Test-driven_development"">Test Driven Development (TDD)</a></strong> as a test-first practice when d
done and part of next upload

2020-12-08 08:11 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Log4j2 for SL4J,Adopt,languages-and-frameworks,FALSE,"<p><strong><a href=""https://logging.apache.org/log4j/2.x/"">Log4j2</a></strong>, our alternate logging framework for java applications.</p>"
Done

2020-12-08 08:12 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Arc42,Adopt,Techniques,FALSE,"<p><strong><a href=""https://docs.arc42.org/home/"">Arc42</a></strong> is our standard way for documenting and communicating software and system architectures.</p>"
All domains are using Arc42, when we analyze later we can decide to remove it as well. Keeping it for now.

2020-12-08 08:14 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +EDB,Adopt,Tools,FALSE,"<p><strong><a href=""https://www.enterprisedb.com/"">EDB</a></strong> as an intermediate tool to migrate from OracleDB to PostgreSQL.</p>"
done

2020-12-08 08:15 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Logback for SL4J,Adopt,languages-and-frameworks,FALSE,"<p><strong><a href=""http://logback.qos.ch/"">Logback</a></strong>, our logging framework for java applications.</p>"
done

2020-12-08 08:16 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Docker,Assess,Tools,FALSE,"<p><strong><a href=""https://www.docker.com/"">Docker</a></strong> is to be used only if a managed <a href=""https://kubernetes.io/"">Kubernetes</a> transparently uses it a
I asked internally too and colleagues are actually using it on local machine. I am keeping it on Assess for now, once we analyze our work in CNT, we can bring it back to hold and provide alternative details.

2020-12-08 08:17 UTC, KrishnanSankaran commented on Lufthansa Systems Tech Radar.csv
> +Feature toggle,Trial,Techniques,FALSE,"<p><strong><a href=""https://www.thoughtworks.com/radar/techniques/simplest-possible-feature-toggle"">Feature toggles</a></strong> are powerful technique to mod
done

2020-12-08 20:27 UTC, wagnst approved these changes
Looking good to me! Thanks a ton!

2020-12-09 08:45 UTC, merged